version: '3'
services:
  app:
    image: node:16.13-alpine
    working_dir: /app
    command: npm run start:dev
    ports:
      - '3000:3000'   
    volumes:
      - '.:/app'
    networks:
      - mysqldb
      - app
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mko
    volumes:
      - './schema/:/docker-entrypoint-initdb.d/:rw'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    networks:
      - mysqldb

networks:
  app: {}
  mysqldb: {}
